.PHONY: run help abs

run:
	python main.py -m -s 512 -e 2 -mt resnet50 -bs 256 -dt FP16
	python main.py -m -s 512 -e 2 -mt resnet50 -bs 256 -dt FP32

abs:
	python main.py -m -s 512 -e 2 -mt resnet50 -abs -dt FP16
	python main.py -m -s 512 -e 2 -mt resnet50 -abs -dt FP32

help:
	@echo "==================================================================="
	@echo "GPU-Insights Benchmark Makefile"
	@echo "==================================================================="
	@echo ""
	@echo "Available targets:"
	@echo "  make run      - Run standard ResNet50 benchmarks (FP16 + FP32)"
	@echo "  make abs      - Run ResNet50 with automatic batch size optimization"
	@echo "  make help     - Show this help message"
	@echo ""
	@echo "==================================================================="
	@echo "Quick Start Examples:"
	@echo "==================================================================="
	@echo ""
	@echo "1. Standard benchmark (FP16):"
	@echo "   python main.py -m -s 512 -e 2 -mt resnet50 -bs 256 -dt FP16 -gpu 0"
	@echo ""
	@echo "2. Standard benchmark (FP32):"
	@echo "   python main.py -m -s 512 -e 2 -mt resnet50 -bs 256 -dt FP32 -gpu 0"
	@echo ""
	@echo "3. Auto batch size optimization:"
	@echo "   python main.py -m -s 512 -e 2 -mt resnet50 -abs -dt FP16 -gpu 0"
	@echo ""
	@echo "4. Multi-GPU benchmark:"
	@echo "   python main.py -m -mt resnet50 -bs 1024 -dt FP32 -gpu 0,1"
	@echo ""
	@echo "5. CNN model benchmark:"
	@echo "   python main.py -m -s 512 -e 2 -mt cnn -bs 2048 -dt FP32 -gpu 0"
	@echo ""
	@echo "==================================================================="
	@echo "Command Line Options:"
	@echo "==================================================================="
	@echo "  -m, --manual              Enable manual benchmark mode"
	@echo "  -H, --huawei              Enable Huawei NPU benchmark"
	@echo "  -M, --mthreads            Enable Mthreads GPU benchmark"
	@echo "  -s, --size <MB>           CUDA memory size in MB (default: 1024)"
	@echo "  -e, --epochs <N>          Number of epochs (default: 5)"
	@echo "  -mt, --model <TYPE>       Model type: resnet50 or cnn (default: cnn)"
	@echo "  -dt, --data_type <TYPE>   Data type: FP32, FP16, or BF16 (default: FP32)"
	@echo "  -bs, --batch <SIZE>       Batch size (default: 0 = auto)"
	@echo "  -abs, --auto_batch_size   Auto batch size optimization (ResNet50 only)"
	@echo "  -cudnn, --cudnn_benchmark Enable cuDNN benchmark mode"
	@echo "  -gpu, --gpu_id <ID>       GPU ID(s), e.g., '0' or '0,1' (default: 0)"
	@echo ""
	@echo "==================================================================="
	@echo "Model Information:"
	@echo "==================================================================="
	@echo "  ResNet50:  23.5M parameters"
	@echo "  CNN:       Custom CNN model"
	@echo ""
	@echo "Recommended batch sizes:"
	@echo "  Multi-GPU FP16: -bs 2048"
	@echo "  Multi-GPU FP32: -bs 1024"
	@echo "  Single GPU:     -bs 256 (or use -abs for auto)"
	@echo ""
	@echo "==================================================================="
	@echo "For more information, visit:"
	@echo "  https://xiaoran007.github.io/GPU-Insights/"
	@echo "==================================================================="